// Automatically generated by MockGen. DO NOT EDIT!
// Source: client.go

package internal

import (
	gomock "github.com/golang/mock/gomock"
)

// Mock of Client interface
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *_MockClientRecorder
}

// Recorder for MockClient (not exported)
type _MockClientRecorder struct {
	mock *MockClient
}

func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &_MockClientRecorder{mock}
	return mock
}

func (_m *MockClient) EXPECT() *_MockClientRecorder {
	return _m.recorder
}

func (_m *MockClient) GetID() string {
	ret := _m.ctrl.Call(_m, "GetID")
	ret0, _ := ret[0].(string)
	return ret0
}

func (_mr *_MockClientRecorder) GetID() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetID")
}

func (_m *MockClient) CompareSecretWith(secret []byte) bool {
	ret := _m.ctrl.Call(_m, "CompareSecretWith", secret)
	ret0, _ := ret[0].(bool)
	return ret0
}

func (_mr *_MockClientRecorder) CompareSecretWith(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CompareSecretWith", arg0)
}

func (_m *MockClient) GetHashedSecret() []byte {
	ret := _m.ctrl.Call(_m, "GetHashedSecret")
	ret0, _ := ret[0].([]byte)
	return ret0
}

func (_mr *_MockClientRecorder) GetHashedSecret() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetHashedSecret")
}

func (_m *MockClient) GetRedirectURIs() []string {
	ret := _m.ctrl.Call(_m, "GetRedirectURIs")
	ret0, _ := ret[0].([]string)
	return ret0
}

func (_mr *_MockClientRecorder) GetRedirectURIs() *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetRedirectURIs")
}
