// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ory-am/fosite/handler/core/refresh (interfaces: RefreshTokenGrantStorage)

package internal

import (
	gomock "github.com/golang/mock/gomock"
	fosite "github.com/ory-am/fosite"
	context "golang.org/x/net/context"
)

// Mock of RefreshTokenGrantStorage interface
type MockRefreshTokenGrantStorage struct {
	ctrl     *gomock.Controller
	recorder *_MockRefreshTokenGrantStorageRecorder
}

// Recorder for MockRefreshTokenGrantStorage (not exported)
type _MockRefreshTokenGrantStorageRecorder struct {
	mock *MockRefreshTokenGrantStorage
}

func NewMockRefreshTokenGrantStorage(ctrl *gomock.Controller) *MockRefreshTokenGrantStorage {
	mock := &MockRefreshTokenGrantStorage{ctrl: ctrl}
	mock.recorder = &_MockRefreshTokenGrantStorageRecorder{mock}
	return mock
}

func (_m *MockRefreshTokenGrantStorage) EXPECT() *_MockRefreshTokenGrantStorageRecorder {
	return _m.recorder
}

func (_m *MockRefreshTokenGrantStorage) CreateRefreshTokenSession(_param0 context.Context, _param1 string, _param2 fosite.Requester) (context.Context, error) {
	ret := _m.ctrl.Call(_m, "CreateRefreshTokenSession", _param0, _param1, _param2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRefreshTokenGrantStorageRecorder) CreateRefreshTokenSession(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateRefreshTokenSession", arg0, arg1, arg2)
}

func (_m *MockRefreshTokenGrantStorage) DeleteRefreshTokenSession(_param0 context.Context, _param1 string) (context.Context, error) {
	ret := _m.ctrl.Call(_m, "DeleteRefreshTokenSession", _param0, _param1)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRefreshTokenGrantStorageRecorder) DeleteRefreshTokenSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteRefreshTokenSession", arg0, arg1)
}

func (_m *MockRefreshTokenGrantStorage) GetRefreshTokenSession(_param0 context.Context, _param1 string, _param2 interface{}) (context.Context, fosite.Requester, error) {
	ret := _m.ctrl.Call(_m, "GetRefreshTokenSession", _param0, _param1, _param2)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(fosite.Requester)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

func (_mr *_MockRefreshTokenGrantStorageRecorder) GetRefreshTokenSession(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetRefreshTokenSession", arg0, arg1, arg2)
}

func (_m *MockRefreshTokenGrantStorage) PersistRefreshTokenGrantSession(_param0 context.Context, _param1 string, _param2 string, _param3 string, _param4 fosite.Requester) (context.Context, error) {
	ret := _m.ctrl.Call(_m, "PersistRefreshTokenGrantSession", _param0, _param1, _param2, _param3, _param4)
	ret0, _ := ret[0].(context.Context)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockRefreshTokenGrantStorageRecorder) PersistRefreshTokenGrantSession(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "PersistRefreshTokenGrantSession", arg0, arg1, arg2, arg3, arg4)
}
