// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ory-am/fosite/handler/core/owner (interfaces: ResourceOwnerPasswordCredentialsGrantStorage)

package internal

import (
	gomock "github.com/golang/mock/gomock"
	fosite "github.com/ory-am/fosite"
)

// Mock of ResourceOwnerPasswordCredentialsGrantStorage interface
type MockResourceOwnerPasswordCredentialsGrantStorage struct {
	ctrl     *gomock.Controller
	recorder *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder
}

// Recorder for MockResourceOwnerPasswordCredentialsGrantStorage (not exported)
type _MockResourceOwnerPasswordCredentialsGrantStorageRecorder struct {
	mock *MockResourceOwnerPasswordCredentialsGrantStorage
}

func NewMockResourceOwnerPasswordCredentialsGrantStorage(ctrl *gomock.Controller) *MockResourceOwnerPasswordCredentialsGrantStorage {
	mock := &MockResourceOwnerPasswordCredentialsGrantStorage{ctrl: ctrl}
	mock.recorder = &_MockResourceOwnerPasswordCredentialsGrantStorageRecorder{mock}
	return mock
}

func (_m *MockResourceOwnerPasswordCredentialsGrantStorage) EXPECT() *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder {
	return _m.recorder
}

func (_m *MockResourceOwnerPasswordCredentialsGrantStorage) CreateAccessTokenSession(_param0 string, _param1 fosite.Requester) error {
	ret := _m.ctrl.Call(_m, "CreateAccessTokenSession", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder) CreateAccessTokenSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "CreateAccessTokenSession", arg0, arg1)
}

func (_m *MockResourceOwnerPasswordCredentialsGrantStorage) DeleteAccessTokenSession(_param0 string) error {
	ret := _m.ctrl.Call(_m, "DeleteAccessTokenSession", _param0)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder) DeleteAccessTokenSession(arg0 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DeleteAccessTokenSession", arg0)
}

func (_m *MockResourceOwnerPasswordCredentialsGrantStorage) DoCredentialsAuthenticate(_param0 string, _param1 string) error {
	ret := _m.ctrl.Call(_m, "DoCredentialsAuthenticate", _param0, _param1)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder) DoCredentialsAuthenticate(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "DoCredentialsAuthenticate", arg0, arg1)
}

func (_m *MockResourceOwnerPasswordCredentialsGrantStorage) GetAccessTokenSession(_param0 string, _param1 interface{}) (fosite.Requester, error) {
	ret := _m.ctrl.Call(_m, "GetAccessTokenSession", _param0, _param1)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockResourceOwnerPasswordCredentialsGrantStorageRecorder) GetAccessTokenSession(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "GetAccessTokenSession", arg0, arg1)
}
