// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite (interfaces: DeviceResponder)

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceResponder is a mock of DeviceResponder interface.
type MockDeviceResponder struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceResponderMockRecorder
}

// MockDeviceResponderMockRecorder is the mock recorder for MockDeviceResponder.
type MockDeviceResponderMockRecorder struct {
	mock *MockDeviceResponder
}

// NewMockDeviceResponder creates a new mock instance.
func NewMockDeviceResponder(ctrl *gomock.Controller) *MockDeviceResponder {
	mock := &MockDeviceResponder{ctrl: ctrl}
	mock.recorder = &MockDeviceResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceResponder) EXPECT() *MockDeviceResponderMockRecorder {
	return m.recorder
}

// GetDeviceCode mocks base method.
func (m *MockDeviceResponder) GetDeviceCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetDeviceCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetDeviceCode indicates an expected call of GetDeviceCode.
func (mr *MockDeviceResponderMockRecorder) GetDeviceCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetDeviceCode", reflect.TypeOf((*MockDeviceResponder)(nil).GetDeviceCode))
}

// GetExpiresIn mocks base method.
func (m *MockDeviceResponder) GetExpiresIn() int64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetExpiresIn")
	ret0, _ := ret[0].(int64)
	return ret0
}

// GetExpiresIn indicates an expected call of GetExpiresIn.
func (mr *MockDeviceResponderMockRecorder) GetExpiresIn() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetExpiresIn", reflect.TypeOf((*MockDeviceResponder)(nil).GetExpiresIn))
}

// GetInterval mocks base method.
func (m *MockDeviceResponder) GetInterval() int {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetInterval")
	ret0, _ := ret[0].(int)
	return ret0
}

// GetInterval indicates an expected call of GetInterval.
func (mr *MockDeviceResponderMockRecorder) GetInterval() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetInterval", reflect.TypeOf((*MockDeviceResponder)(nil).GetInterval))
}

// GetUserCode mocks base method.
func (m *MockDeviceResponder) GetUserCode() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserCode")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetUserCode indicates an expected call of GetUserCode.
func (mr *MockDeviceResponderMockRecorder) GetUserCode() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserCode", reflect.TypeOf((*MockDeviceResponder)(nil).GetUserCode))
}

// GetVerificationURI mocks base method.
func (m *MockDeviceResponder) GetVerificationURI() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationURI")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVerificationURI indicates an expected call of GetVerificationURI.
func (mr *MockDeviceResponderMockRecorder) GetVerificationURI() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationURI", reflect.TypeOf((*MockDeviceResponder)(nil).GetVerificationURI))
}

// GetVerificationURIComplete mocks base method.
func (m *MockDeviceResponder) GetVerificationURIComplete() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetVerificationURIComplete")
	ret0, _ := ret[0].(string)
	return ret0
}

// GetVerificationURIComplete indicates an expected call of GetVerificationURIComplete.
func (mr *MockDeviceResponderMockRecorder) GetVerificationURIComplete() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetVerificationURIComplete", reflect.TypeOf((*MockDeviceResponder)(nil).GetVerificationURIComplete))
}

// SetDeviceCode mocks base method.
func (m *MockDeviceResponder) SetDeviceCode(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetDeviceCode", arg0)
}

// SetDeviceCode indicates an expected call of SetDeviceCode.
func (mr *MockDeviceResponderMockRecorder) SetDeviceCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetDeviceCode", reflect.TypeOf((*MockDeviceResponder)(nil).SetDeviceCode), arg0)
}

// SetExpiresIn mocks base method.
func (m *MockDeviceResponder) SetExpiresIn(arg0 int64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetExpiresIn", arg0)
}

// SetExpiresIn indicates an expected call of SetExpiresIn.
func (mr *MockDeviceResponderMockRecorder) SetExpiresIn(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetExpiresIn", reflect.TypeOf((*MockDeviceResponder)(nil).SetExpiresIn), arg0)
}

// SetInterval mocks base method.
func (m *MockDeviceResponder) SetInterval(arg0 int) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetInterval", arg0)
}

// SetInterval indicates an expected call of SetInterval.
func (mr *MockDeviceResponderMockRecorder) SetInterval(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetInterval", reflect.TypeOf((*MockDeviceResponder)(nil).SetInterval), arg0)
}

// SetUserCode mocks base method.
func (m *MockDeviceResponder) SetUserCode(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetUserCode", arg0)
}

// SetUserCode indicates an expected call of SetUserCode.
func (mr *MockDeviceResponderMockRecorder) SetUserCode(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserCode", reflect.TypeOf((*MockDeviceResponder)(nil).SetUserCode), arg0)
}

// SetVerificationURI mocks base method.
func (m *MockDeviceResponder) SetVerificationURI(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerificationURI", arg0)
}

// SetVerificationURI indicates an expected call of SetVerificationURI.
func (mr *MockDeviceResponderMockRecorder) SetVerificationURI(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerificationURI", reflect.TypeOf((*MockDeviceResponder)(nil).SetVerificationURI), arg0)
}

// SetVerificationURIComplete mocks base method.
func (m *MockDeviceResponder) SetVerificationURIComplete(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "SetVerificationURIComplete", arg0)
}

// SetVerificationURIComplete indicates an expected call of SetVerificationURIComplete.
func (mr *MockDeviceResponderMockRecorder) SetVerificationURIComplete(arg0 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetVerificationURIComplete", reflect.TypeOf((*MockDeviceResponder)(nil).SetVerificationURIComplete), arg0)
}
