// Copyright © 2023 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite (interfaces: DeviceAuthorizeResponder)

// Package internal is a generated GoMock package.
package internal

import (
	http "net/http"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
)

// MockDeviceAuthorizeResponder is a mock of DeviceAuthorizeResponder interface.
type MockDeviceAuthorizeResponder struct {
	ctrl     *gomock.Controller
	recorder *MockDeviceAuthorizeResponderMockRecorder
}

// MockDeviceAuthorizeResponderMockRecorder is the mock recorder for MockDeviceAuthorizeResponder.
type MockDeviceAuthorizeResponderMockRecorder struct {
	mock *MockDeviceAuthorizeResponder
}

// NewMockDeviceAuthorizeResponder creates a new mock instance.
func NewMockDeviceAuthorizeResponder(ctrl *gomock.Controller) *MockDeviceAuthorizeResponder {
	mock := &MockDeviceAuthorizeResponder{ctrl: ctrl}
	mock.recorder = &MockDeviceAuthorizeResponderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDeviceAuthorizeResponder) EXPECT() *MockDeviceAuthorizeResponderMockRecorder {
	return m.recorder
}

// AddHeader mocks base method.
func (m *MockDeviceAuthorizeResponder) AddHeader(arg0, arg1 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AddHeader", arg0, arg1)
}

// AddHeader indicates an expected call of AddHeader.
func (mr *MockDeviceAuthorizeResponderMockRecorder) AddHeader(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddHeader", reflect.TypeOf((*MockDeviceAuthorizeResponder)(nil).AddHeader), arg0, arg1)
}

// GetHeader mocks base method.
func (m *MockDeviceAuthorizeResponder) GetHeader() http.Header {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetHeader")
	ret0, _ := ret[0].(http.Header)
	return ret0
}

// GetHeader indicates an expected call of GetHeader.
func (mr *MockDeviceAuthorizeResponderMockRecorder) GetHeader() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetHeader", reflect.TypeOf((*MockDeviceAuthorizeResponder)(nil).GetHeader))
}
