// Automatically generated by MockGen. DO NOT EDIT!
// Source: handler.go

package internal

import (
	gomock "github.com/golang/mock/gomock"
	. "github.com/ory-am/fosite"
	context "golang.org/x/net/context"
	http "net/http"
)

// Mock of AuthorizeEndpointHandler interface
type MockAuthorizeEndpointHandler struct {
	ctrl     *gomock.Controller
	recorder *_MockAuthorizeEndpointHandlerRecorder
}

// Recorder for MockAuthorizeEndpointHandler (not exported)
type _MockAuthorizeEndpointHandlerRecorder struct {
	mock *MockAuthorizeEndpointHandler
}

func NewMockAuthorizeEndpointHandler(ctrl *gomock.Controller) *MockAuthorizeEndpointHandler {
	mock := &MockAuthorizeEndpointHandler{ctrl: ctrl}
	mock.recorder = &_MockAuthorizeEndpointHandlerRecorder{mock}
	return mock
}

func (_m *MockAuthorizeEndpointHandler) EXPECT() *_MockAuthorizeEndpointHandlerRecorder {
	return _m.recorder
}

func (_m *MockAuthorizeEndpointHandler) HandleAuthorizeRequest(ctx context.Context, responder AuthorizeResponder, requester AuthorizeRequester, req *http.Request, session interface{}) error {
	ret := _m.ctrl.Call(_m, "HandleAuthorizeRequest", ctx, responder, requester, req, session)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockAuthorizeEndpointHandlerRecorder) HandleAuthorizeRequest(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "HandleAuthorizeRequest", arg0, arg1, arg2, arg3, arg4)
}
