// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ory/fosite (interfaces: Hasher)

package internal

import (
	context "context"
	gomock "github.com/golang/mock/gomock"
)

// Mock of Hasher interface
type MockHasher struct {
	ctrl     *gomock.Controller
	recorder *_MockHasherRecorder
}

// Recorder for MockHasher (not exported)
type _MockHasherRecorder struct {
	mock *MockHasher
}

func NewMockHasher(ctrl *gomock.Controller) *MockHasher {
	mock := &MockHasher{ctrl: ctrl}
	mock.recorder = &_MockHasherRecorder{mock}
	return mock
}

func (_m *MockHasher) EXPECT() *_MockHasherRecorder {
	return _m.recorder
}

func (_m *MockHasher) Compare(_param0 context.Context, _param1 []byte, _param2 []byte) error {
	ret := _m.ctrl.Call(_m, "Compare", _param0, _param1, _param2)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockHasherRecorder) Compare(arg0, arg1, arg2 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Compare", arg0, arg1, arg2)
}

func (_m *MockHasher) Hash(_param0 context.Context, _param1 []byte) ([]byte, error) {
	ret := _m.ctrl.Call(_m, "Hash", _param0, _param1)
	ret0, _ := ret[0].([]byte)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

func (_mr *_MockHasherRecorder) Hash(arg0, arg1 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "Hash", arg0, arg1)
}
