// Copyright © 2022 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: storage.go

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	fosite "github.com/ory/fosite"
	jwt "github.com/ory/fosite/token/jwt"
)

// MockRFC8693Storage is a mock of RFC8693Storage interface.
type MockRFC8693Storage struct {
	ctrl     *gomock.Controller
	recorder *MockRFC8693StorageMockRecorder
}

// MockRFC8693StorageMockRecorder is the mock recorder for MockRFC8693Storage.
type MockRFC8693StorageMockRecorder struct {
	mock *MockRFC8693Storage
}

// NewMockRFC8693Storage creates a new mock instance.
func NewMockRFC8693Storage(ctrl *gomock.Controller) *MockRFC8693Storage {
	mock := &MockRFC8693Storage{ctrl: ctrl}
	mock.recorder = &MockRFC8693StorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRFC8693Storage) EXPECT() *MockRFC8693StorageMockRecorder {
	return m.recorder
}

// GetAllowedClientIDs mocks base method.
func (m *MockRFC8693Storage) GetAllowedClientIDs(ctx context.Context, clientID string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAllowedClientIDs", ctx, clientID)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetAllowedClientIDs indicates an expected call of GetAllowedClientIDs.
func (mr *MockRFC8693StorageMockRecorder) GetAllowedClientIDs(ctx, clientID interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAllowedClientIDs", reflect.TypeOf((*MockRFC8693Storage)(nil).GetAllowedClientIDs), ctx, clientID)
}

// GetIDTokenPublicKey mocks base method.
func (m *MockRFC8693Storage) GetIDTokenPublicKey(ctx context.Context, iss, kid string) (interface{}, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetIDTokenPublicKey", ctx, iss, kid)
	ret0, _ := ret[0].(interface{})
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetIDTokenPublicKey indicates an expected call of GetIDTokenPublicKey.
func (mr *MockRFC8693StorageMockRecorder) GetIDTokenPublicKey(ctx, iss, kid interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetIDTokenPublicKey", reflect.TypeOf((*MockRFC8693Storage)(nil).GetIDTokenPublicKey), ctx, iss, kid)
}

// GetImpersonateSubject mocks base method.
func (m *MockRFC8693Storage) GetImpersonateSubject(ctx context.Context, claims jwt.MapClaims, req fosite.Requester) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetImpersonateSubject", ctx, claims, req)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetImpersonateSubject indicates an expected call of GetImpersonateSubject.
func (mr *MockRFC8693StorageMockRecorder) GetImpersonateSubject(ctx, claims, req interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetImpersonateSubject", reflect.TypeOf((*MockRFC8693Storage)(nil).GetImpersonateSubject), ctx, claims, req)
}
