// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite/handler/openid (interfaces: OIDCRequestStorageProvider)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/oidc_request_storage_provider.go github.com/ory/fosite/handler/openid OIDCRequestStorageProvider
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	openid "github.com/ory/fosite/handler/openid"
	gomock "go.uber.org/mock/gomock"
)

// MockOIDCRequestStorageProvider is a mock of OIDCRequestStorageProvider interface.
type MockOIDCRequestStorageProvider struct {
	ctrl     *gomock.Controller
	recorder *MockOIDCRequestStorageProviderMockRecorder
	isgomock struct{}
}

// MockOIDCRequestStorageProviderMockRecorder is the mock recorder for MockOIDCRequestStorageProvider.
type MockOIDCRequestStorageProviderMockRecorder struct {
	mock *MockOIDCRequestStorageProvider
}

// NewMockOIDCRequestStorageProvider creates a new mock instance.
func NewMockOIDCRequestStorageProvider(ctrl *gomock.Controller) *MockOIDCRequestStorageProvider {
	mock := &MockOIDCRequestStorageProvider{ctrl: ctrl}
	mock.recorder = &MockOIDCRequestStorageProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockOIDCRequestStorageProvider) EXPECT() *MockOIDCRequestStorageProviderMockRecorder {
	return m.recorder
}

// OpenIDConnectRequestStorage mocks base method.
func (m *MockOIDCRequestStorageProvider) OpenIDConnectRequestStorage() openid.OIDCRequestStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenIDConnectRequestStorage")
	ret0, _ := ret[0].(openid.OIDCRequestStorage)
	return ret0
}

// OpenIDConnectRequestStorage indicates an expected call of OpenIDConnectRequestStorage.
func (mr *MockOIDCRequestStorageProviderMockRecorder) OpenIDConnectRequestStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenIDConnectRequestStorage", reflect.TypeOf((*MockOIDCRequestStorageProvider)(nil).OpenIDConnectRequestStorage))
}
