// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite/handler/openid (interfaces: RequestStorage)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/openid_id_token_storage.go github.com/ory/fosite/handler/openid RequestStorage
//

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	fosite "github.com/ory/fosite"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestStorage is a mock of RequestStorage interface.
type MockRequestStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRequestStorageMockRecorder
	isgomock struct{}
}

// MockRequestStorageMockRecorder is the mock recorder for MockRequestStorage.
type MockRequestStorageMockRecorder struct {
	mock *MockRequestStorage
}

// NewMockRequestStorage creates a new mock instance.
func NewMockRequestStorage(ctrl *gomock.Controller) *MockRequestStorage {
	mock := &MockRequestStorage{ctrl: ctrl}
	mock.recorder = &MockRequestStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestStorage) EXPECT() *MockRequestStorageMockRecorder {
	return m.recorder
}

// CreateOpenIDConnectSession mocks base method.
func (m *MockRequestStorage) CreateOpenIDConnectSession(ctx context.Context, authorizeCode string, requester fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateOpenIDConnectSession", ctx, authorizeCode, requester)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreateOpenIDConnectSession indicates an expected call of CreateOpenIDConnectSession.
func (mr *MockRequestStorageMockRecorder) CreateOpenIDConnectSession(ctx, authorizeCode, requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateOpenIDConnectSession", reflect.TypeOf((*MockRequestStorage)(nil).CreateOpenIDConnectSession), ctx, authorizeCode, requester)
}

// DeleteOpenIDConnectSession mocks base method.
func (m *MockRequestStorage) DeleteOpenIDConnectSession(ctx context.Context, authorizeCode string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteOpenIDConnectSession", ctx, authorizeCode)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteOpenIDConnectSession indicates an expected call of DeleteOpenIDConnectSession.
func (mr *MockRequestStorageMockRecorder) DeleteOpenIDConnectSession(ctx, authorizeCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteOpenIDConnectSession", reflect.TypeOf((*MockRequestStorage)(nil).DeleteOpenIDConnectSession), ctx, authorizeCode)
}

// GetOpenIDConnectSession mocks base method.
func (m *MockRequestStorage) GetOpenIDConnectSession(ctx context.Context, authorizeCode string, requester fosite.Requester) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenIDConnectSession", ctx, authorizeCode, requester)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenIDConnectSession indicates an expected call of GetOpenIDConnectSession.
func (mr *MockRequestStorageMockRecorder) GetOpenIDConnectSession(ctx, authorizeCode, requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenIDConnectSession", reflect.TypeOf((*MockRequestStorage)(nil).GetOpenIDConnectSession), ctx, authorizeCode, requester)
}
