// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite/handler/pkce (interfaces: RequestStorage)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/pkce_storage_strategy.go github.com/ory/fosite/handler/pkce RequestStorage
//

// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	fosite "github.com/ory/fosite"
	gomock "go.uber.org/mock/gomock"
)

// MockRequestStorage is a mock of RequestStorage interface.
type MockRequestStorage struct {
	ctrl     *gomock.Controller
	recorder *MockRequestStorageMockRecorder
	isgomock struct{}
}

// MockRequestStorageMockRecorder is the mock recorder for MockRequestStorage.
type MockRequestStorageMockRecorder struct {
	mock *MockRequestStorage
}

// NewMockRequestStorage creates a new mock instance.
func NewMockRequestStorage(ctrl *gomock.Controller) *MockRequestStorage {
	mock := &MockRequestStorage{ctrl: ctrl}
	mock.recorder = &MockRequestStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRequestStorage) EXPECT() *MockRequestStorageMockRecorder {
	return m.recorder
}

// CreatePKCERequestSession mocks base method.
func (m *MockRequestStorage) CreatePKCERequestSession(ctx context.Context, signature string, requester fosite.Requester) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePKCERequestSession", ctx, signature, requester)
	ret0, _ := ret[0].(error)
	return ret0
}

// CreatePKCERequestSession indicates an expected call of CreatePKCERequestSession.
func (mr *MockRequestStorageMockRecorder) CreatePKCERequestSession(ctx, signature, requester any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePKCERequestSession", reflect.TypeOf((*MockRequestStorage)(nil).CreatePKCERequestSession), ctx, signature, requester)
}

// DeletePKCERequestSession mocks base method.
func (m *MockRequestStorage) DeletePKCERequestSession(ctx context.Context, signature string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeletePKCERequestSession", ctx, signature)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeletePKCERequestSession indicates an expected call of DeletePKCERequestSession.
func (mr *MockRequestStorageMockRecorder) DeletePKCERequestSession(ctx, signature any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeletePKCERequestSession", reflect.TypeOf((*MockRequestStorage)(nil).DeletePKCERequestSession), ctx, signature)
}

// GetPKCERequestSession mocks base method.
func (m *MockRequestStorage) GetPKCERequestSession(ctx context.Context, signature string, session fosite.Session) (fosite.Requester, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPKCERequestSession", ctx, signature, session)
	ret0, _ := ret[0].(fosite.Requester)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPKCERequestSession indicates an expected call of GetPKCERequestSession.
func (mr *MockRequestStorageMockRecorder) GetPKCERequestSession(ctx, signature, session any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPKCERequestSession", reflect.TypeOf((*MockRequestStorage)(nil).GetPKCERequestSession), ctx, signature, session)
}
