// Copyright © 2024 Ory Corp
// SPDX-License-Identifier: Apache-2.0

// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite/handler/rfc8628 (interfaces: RFC8628CodeStrategy)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/rfc8628_code_strategy.go github.com/ory/fosite/handler/rfc8628 RFC8628CodeStrategy
//
// Package internal is a generated GoMock package.
package internal

import (
	context "context"
	reflect "reflect"

	fosite "github.com/ory/fosite"
	gomock "go.uber.org/mock/gomock"
)

// MockRFC8628CodeStrategy is a mock of RFC8628CodeStrategy interface.
type MockRFC8628CodeStrategy struct {
	ctrl     *gomock.Controller
	recorder *MockRFC8628CodeStrategyMockRecorder
}

// MockRFC8628CodeStrategyMockRecorder is the mock recorder for MockRFC8628CodeStrategy.
type MockRFC8628CodeStrategyMockRecorder struct {
	mock *MockRFC8628CodeStrategy
}

// NewMockRFC8628CodeStrategy creates a new mock instance.
func NewMockRFC8628CodeStrategy(ctrl *gomock.Controller) *MockRFC8628CodeStrategy {
	mock := &MockRFC8628CodeStrategy{ctrl: ctrl}
	mock.recorder = &MockRFC8628CodeStrategyMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockRFC8628CodeStrategy) EXPECT() *MockRFC8628CodeStrategyMockRecorder {
	return m.recorder
}

// DeviceCodeSignature mocks base method.
func (m *MockRFC8628CodeStrategy) DeviceCodeSignature(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceCodeSignature", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeviceCodeSignature indicates an expected call of DeviceCodeSignature.
func (mr *MockRFC8628CodeStrategyMockRecorder) DeviceCodeSignature(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceCodeSignature", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).DeviceCodeSignature), arg0, arg1)
}

// GenerateDeviceCode mocks base method.
func (m *MockRFC8628CodeStrategy) GenerateDeviceCode(arg0 context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateDeviceCode", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateDeviceCode indicates an expected call of GenerateDeviceCode.
func (mr *MockRFC8628CodeStrategyMockRecorder) GenerateDeviceCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateDeviceCode", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).GenerateDeviceCode), arg0)
}

// GenerateUserCode mocks base method.
func (m *MockRFC8628CodeStrategy) GenerateUserCode(arg0 context.Context) (string, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GenerateUserCode", arg0)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// GenerateUserCode indicates an expected call of GenerateUserCode.
func (mr *MockRFC8628CodeStrategyMockRecorder) GenerateUserCode(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GenerateUserCode", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).GenerateUserCode), arg0)
}

// ShouldRateLimit mocks base method.
func (m *MockRFC8628CodeStrategy) ShouldRateLimit(arg0 context.Context, arg1 string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ShouldRateLimit", arg0, arg1)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ShouldRateLimit indicates an expected call of ShouldRateLimit.
func (mr *MockRFC8628CodeStrategyMockRecorder) ShouldRateLimit(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ShouldRateLimit", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).ShouldRateLimit), arg0, arg1)
}

// UserCodeSignature mocks base method.
func (m *MockRFC8628CodeStrategy) UserCodeSignature(arg0 context.Context, arg1 string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UserCodeSignature", arg0, arg1)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// UserCodeSignature indicates an expected call of UserCodeSignature.
func (mr *MockRFC8628CodeStrategyMockRecorder) UserCodeSignature(arg0, arg1 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UserCodeSignature", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).UserCodeSignature), arg0, arg1)
}

// ValidateDeviceCode mocks base method.
func (m *MockRFC8628CodeStrategy) ValidateDeviceCode(arg0 context.Context, arg1 fosite.Requester, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateDeviceCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateDeviceCode indicates an expected call of ValidateDeviceCode.
func (mr *MockRFC8628CodeStrategyMockRecorder) ValidateDeviceCode(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateDeviceCode", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).ValidateDeviceCode), arg0, arg1, arg2)
}

// ValidateUserCode mocks base method.
func (m *MockRFC8628CodeStrategy) ValidateUserCode(arg0 context.Context, arg1 fosite.Requester, arg2 string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ValidateUserCode", arg0, arg1, arg2)
	ret0, _ := ret[0].(error)
	return ret0
}

// ValidateUserCode indicates an expected call of ValidateUserCode.
func (mr *MockRFC8628CodeStrategyMockRecorder) ValidateUserCode(arg0, arg1, arg2 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ValidateUserCode", reflect.TypeOf((*MockRFC8628CodeStrategy)(nil).ValidateUserCode), arg0, arg1, arg2)
}
