// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/ory/fosite/handler/rfc8628 (interfaces: Storage)
//
// Generated by this command:
//
//	mockgen -package internal -destination internal/rfc8628_core_storage.go github.com/ory/fosite/handler/rfc8628 Storage
//

// Package internal is a generated GoMock package.
package internal

import (
	reflect "reflect"

	oauth2 "github.com/ory/fosite/handler/oauth2"
	rfc8628 "github.com/ory/fosite/handler/rfc8628"
	gomock "go.uber.org/mock/gomock"
)

// MockStorage is a mock of Storage interface.
type MockStorage struct {
	ctrl     *gomock.Controller
	recorder *MockStorageMockRecorder
	isgomock struct{}
}

// MockStorageMockRecorder is the mock recorder for MockStorage.
type MockStorageMockRecorder struct {
	mock *MockStorage
}

// NewMockStorage creates a new mock instance.
func NewMockStorage(ctrl *gomock.Controller) *MockStorage {
	mock := &MockStorage{ctrl: ctrl}
	mock.recorder = &MockStorageMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStorage) EXPECT() *MockStorageMockRecorder {
	return m.recorder
}

// AccessTokenStorage mocks base method.
func (m *MockStorage) AccessTokenStorage() oauth2.AccessTokenStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AccessTokenStorage")
	ret0, _ := ret[0].(oauth2.AccessTokenStorage)
	return ret0
}

// AccessTokenStorage indicates an expected call of AccessTokenStorage.
func (mr *MockStorageMockRecorder) AccessTokenStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AccessTokenStorage", reflect.TypeOf((*MockStorage)(nil).AccessTokenStorage))
}

// DeviceAuthStorage mocks base method.
func (m *MockStorage) DeviceAuthStorage() rfc8628.DeviceAuthStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeviceAuthStorage")
	ret0, _ := ret[0].(rfc8628.DeviceAuthStorage)
	return ret0
}

// DeviceAuthStorage indicates an expected call of DeviceAuthStorage.
func (mr *MockStorageMockRecorder) DeviceAuthStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeviceAuthStorage", reflect.TypeOf((*MockStorage)(nil).DeviceAuthStorage))
}

// RefreshTokenStorage mocks base method.
func (m *MockStorage) RefreshTokenStorage() oauth2.RefreshTokenStorage {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RefreshTokenStorage")
	ret0, _ := ret[0].(oauth2.RefreshTokenStorage)
	return ret0
}

// RefreshTokenStorage indicates an expected call of RefreshTokenStorage.
func (mr *MockStorageMockRecorder) RefreshTokenStorage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RefreshTokenStorage", reflect.TypeOf((*MockStorage)(nil).RefreshTokenStorage))
}
