// Automatically generated by MockGen. DO NOT EDIT!
// Source: github.com/ory-am/fosite (interfaces: TokenValidator)

package internal

import (
	gomock "github.com/golang/mock/gomock"
	fosite "github.com/ory-am/fosite"
	context "golang.org/x/net/context"
)

// Mock of TokenValidator interface
type MockTokenValidator struct {
	ctrl     *gomock.Controller
	recorder *_MockTokenValidatorRecorder
}

// Recorder for MockTokenValidator (not exported)
type _MockTokenValidatorRecorder struct {
	mock *MockTokenValidator
}

func NewMockTokenValidator(ctrl *gomock.Controller) *MockTokenValidator {
	mock := &MockTokenValidator{ctrl: ctrl}
	mock.recorder = &_MockTokenValidatorRecorder{mock}
	return mock
}

func (_m *MockTokenValidator) EXPECT() *_MockTokenValidatorRecorder {
	return _m.recorder
}

func (_m *MockTokenValidator) ValidateToken(_param0 context.Context, _param1 string, _param2 fosite.TokenType, _param3 fosite.AccessRequester, _param4 []string) error {
	ret := _m.ctrl.Call(_m, "ValidateToken", _param0, _param1, _param2, _param3, _param4)
	ret0, _ := ret[0].(error)
	return ret0
}

func (_mr *_MockTokenValidatorRecorder) ValidateToken(arg0, arg1, arg2, arg3, arg4 interface{}) *gomock.Call {
	return _mr.mock.ctrl.RecordCall(_mr.mock, "ValidateToken", arg0, arg1, arg2, arg3, arg4)
}
